controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

contact:
    path: /contact
    controller: App\Controller\ContactController::contact

success_page:
    path: /success
    controller: App\Controller\ContactController::success
